# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 300

services:
  nacos:
    image: nacos/nacos-server:2.0.0
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - JVM_XMS=350m
      - JVM_XMX=350m
      - JVM_XMN=150m
    healthcheck:
      test: 'curl -Ss http://localhost:8848/nacos'
      interval: 5s
      timeout: 5s
      retries: 40

  dubbo-samples-nacos-conditionrouter1:
    type: app
    basedir: .
    mainClass: org.apache.dubbo.samples.governance.BasicProvider
    systemProps:
      - nacos.address=nacos
      - nacos.port=8848
      - dubbo.port=20880
    waitPortsBeforeRun:
      - nacos:8848
    checkPorts:
      - 20880
    checkLog: "dubbo service started"
    depends_on:
      - nacos

  dubbo-samples-nacos-conditionrouter2:
    type: app
    basedir: .
    mainClass: org.apache.dubbo.samples.governance.BasicProvider
    systemProps:
      - nacos.address=nacos
      - nacos.port=8848
      - dubbo.port=20881
    waitPortsBeforeRun:
      - nacos:8848
    checkPorts:
      - 20881
    checkLog: "dubbo service started"
    depends_on:
      - nacos

  dubbo-samples-nacos-conditionrouter-test:
    type: test
    basedir: .
    tests:
      - "**/*IT.class"
    systemProps:
      - nacos.address=nacos
      - nacos.port=8848
    waitPortsBeforeRun:
      - nacos:8848
      - dubbo-samples-nacos-conditionrouter1:20880
      - dubbo-samples-nacos-conditionrouter2:20881
    depends_on:
      - nacos
      - dubbo-samples-nacos-conditionrouter1
      - dubbo-samples-nacos-conditionrouter2
