spring:
    application:
        name: StockApplication
dubbo:
  application:
    logger: slf4j
    name: ${spring.application.name}
  registry:
    address: multicast://224.5.6.7:1234
seata:
    enabled: true
    application-id: dubbo-samples-seata
    tx-service-group: my_test_tx_group
    service:
        vgroup-mapping:
            my_test_tx_group: default
        grouplist:
            default: 127.0.0.1:8091
    registry:
        type: file
    config:
        type: file
