# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

my-address: 127.0.0.1

spring:
    application:
        name: dubbo-springboot3-tracing-cunsumer
dubbo:
    application:
        name: ${spring.application.name}
    protocol:
        name: dubbo
        port: -1
    registry:
        id: nacos-registry
        address: nacos://${my-address}:8848
    config-center:
        address: nacos://${my-address}:8848
    metadata-report:
        address: nacos://${my-address}:8848
    tracing:
        enabled: true # default is false
        sampling:
            probability: 0.5 # sampling rate, default is 0.1
        propagation:
            type: W3C # W3C/B3 default is W3C
        tracing-exporter:
            zipkin-config:
                endpoint: http://${my-address}:9411/api/v2/spans
                connect-timeout: 1s # connect timeout, default is 1s
                read-timeout: 10s # read timeout, default is 10s

logging:
    level:
        root: info
    pattern:
        console: '[%d{dd/MM/yy HH:mm:ss:SSS z}] %t %5p %c{2} [%X{traceId:-}, %X{spanId:-}]: %m%n'
