server:
  port: 50000

dubbo:
  application:
    logger: slf4j
    qos-enable: false
    check-serializable: false
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
  protocol:
    port: 20883
    name: dubbo