dubbo:
  application:
    logger: slf4j
    name: ConsumerApplication
  registry:
    address: nacos://${nacos.address:192.168.10.10}:8848
  protocol:
    name: tri
    port: 50051
server:
  port: 9012
