# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  zookeeper:
    image: zookeeper:latest

  dubbo-samples-conditionrouterv31-1:
    type: app
    basedir: .
    mainClass: org.apache.dubbo.samples.governance.BasicProvider
    systemProps:
      - zookeeper.address=zookeeper
      - zookeeper.port=2181
      - dubbo.port=28080
    waitPortsBeforeRun:
      - zookeeper:2181
    checkPorts:
      - 28080
    checkLog: "dubbo service started"
    depends_on:
      - zookeeper

  dubbo-samples-conditionrouterv31-2:
    type: app
    basedir: .
    mainClass: org.apache.dubbo.samples.governance.BasicProvider28081
    systemProps:
      - zookeeper.address=zookeeper
      - zookeeper.port=2181
      - dubbo.port=28081
    waitPortsBeforeRun:
      - zookeeper:2181
    checkPorts:
      - 28081
    checkLog: "dubbo service started"
    depends_on:
      - zookeeper

  dubbo-samples-configconditionrouter-test:
    type: test
    basedir: .
    tests:
      - "**/*IT.class"
    systemProps:
      - zookeeper.address=zookeeper
      - zookeeper.port=2181
    waitPortsBeforeRun:
      - zookeeper:2181
      - dubbo-samples-conditionrouterv31-1:28080
      - dubbo-samples-conditionrouterv31-2:28081
    depends_on:
      - zookeeper
      - dubbo-samples-conditionrouterv31-1
      - dubbo-samples-conditionrouterv31-2
