#Common Config
#    dubbo:
#    application:
#        qos-enable: false
#    registries:
#        beijingRegistry:
#             address: zookeeper://localhost:2181
#        shanghaiRegistry:
#             address: zookeeper://localhost:2182
#    protocol:
#        name: dubbo
#        port: 20885
# If the address of your registry you set is exactly the same (including the port number), you need to set one of the default properties
dubbo:
    application:
        qos-enable: false
        name: multi-registry-consumer
    registries:
        beijingRegistry:
            default: false
            address: zookeeper://${zookeeper.address.1:127.0.0.1}:${zookeeper.port:2181}
        shanghaiRegistry:
            address: zookeeper://${zookeeper.address.2:127.0.0.1}:${zookeeper.port:2181}
    protocol:
        name: dubbo
        port: 20884
