
dubbo:
  application:
    name: direct-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  provider:
    token: "true"