dubbo:
    application:
        logger: logback
        name: DemoApplication
    registry:
        address: nacos://${nacos.address:192.168.10.10}:8848
    protocol:
        name: tri
        port: 50051
        serialization: fastjson2
    provider:
        serialization: fastjson2
    consumer:
        serialization: fastjson2
server:
    port: 9011
