spring:
  application:
    name: dubbo-springboot-triple-custom-uri
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: tri
    port: 50052
    triple:
      verbose: true
