# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ignoreFor: 'Interoperability between spring-cloud and dubbo is not ready?'

services:
  nacos-server:
    image: nacos/nacos-server:2.0.0
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m

  dubbo-provider:
    type: app
    basedir: dubbo-provider
    mainClass: org.apache.dubbo.demo.provider.Application
    waitPortsBeforeRun:
      - nacos-server:8848
    checkPorts:
      - 8090
    checkLog: "dubbo service started"
    depends_on:
      - nacos-server

  sc-consumer:
    type: app
    basedir: sc-consumer
    mainClass: org.apache.dubbo.samples.microservices.sc.Application
    waitPortsBeforeRun:
      - nacos-server:8848
    checkPorts:
      - 8099
    checkLog: "sc-consumer started"
    depends_on:
      - nacos-server

  sc-dubbo-consumer-test:
    type: test
    basedir: sc-consumer
    tests:
      - "**/*IT.class"
    systemProps:
      - nacos.address=nacos-server
      - consumer.address=sc-consumer
    waitPortsBeforeRun:
      - nacos-server:8848
      - dubbo-provider:8090
      - sc-consumer:8099
    depends_on:
      - nacos-server
      - dubbo-provider
      - sc-consumer
