# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Deployment
apiVersion: apps/v1
metadata:
	name: nacos-server
spec:
	replicas: 1
	selector:
		matchLabels:
			app: nacos-server
	template:
		metadata:
			labels:
				app: nacos-server
		spec:
			containers:
				- env:
					  - name: MODE
						value: standalone
				  image: nacos/nacos-server:v2.2.0
				  imagePullPolicy: Always
				  name: nacos-server
				  ports:
					  - containerPort: 8848
					    name: client
					  - containerPort: 9848
					    name: client-rpc
					  - containerPort: 9849
					    name: raft-rpc
					  - containerPort: 7848
					    name: old-raft-rpc
			dnsPolicy: ClusterFirst
			restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
	name: nacos-server
spec:
	ports:
		- port: 8848
		  name: server
		  protocol: TCP
		  targetPort: 8848
	selector:
		app: nacos-server
	type: ClusterIP