kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dubbo-sa-rolebinding
subjects:
- kind: ServiceAccount
  name: dubbo-sa
roleRef:
  kind: Role
  name: dubbo-role
  apiGroup: rbac.authorization.k8s.io
