# Using Oracle GraalVM for JDK 17
FROM container-registry.oracle.com/graalvm/jdk:17-ol8

RUN ./mvnw clean package

# JAR file will be specified by passing in a build time argument to docker build
ARG APP_FILE

EXPOSE 50052

# opy the JAR file into the root and rename
COPY ./target/${APP_FILE} app.jar

# Run java with the jar file when the container starts up
CMD ["java","-jar","app.jar"]