name: License Check

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  license:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check License
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
